Run CI on testing-farm
Updating CI to run on testing-farm.
alpine is not available on testing-farm so it will
continue to run as before.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,14 +1,13 @@
-name: Confirm tests run successfully
-
-on:
+on: 
   push:
     branches:
       - main
-  pull_request:
+  pull_request_target:
+    types: [opened, synchronize, reopened]
 
 jobs:
-  build:
-    name: Verify tests pass
+  testing-farm:
+    name: Verify tests pass (tf)
 
     runs-on: ubuntu-latest
 
@@ -17,98 +16,122 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        container_image:
-          - docker.io/library/alpine:latest
-          - docker.io/library/alpine:edge
-          - quay.io/centos/centos:stream9
-          - quay.io/centos/centos:stream10
-          - registry.fedoraproject.org/fedora:40
-          - registry.fedoraproject.org/fedora:41
-          - registry.fedoraproject.org/fedora:rawhide
-          - registry.access.redhat.com/ubi8
-          - registry.access.redhat.com/ubi9
+        compose:
+          - CentOS-Stream-9
+          - CentOS-Stream-10
+          - Fedora-40
+          - Fedora-41
         dotnet_version:
           - "8.0"
           - "9.0"
-        exclude:
-          - container_image: docker.io/library/alpine:latest
-            dotnet_version: "9.0"
-          - container_image: docker.io/library/alpine:edge
-            dotnet_version: "9.0"
-
-    container:
-      image: ${{ matrix.container_image }}
-      options: --security-opt seccomp=unconfined
+        arch:
+          - x86_64
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Get User Permission
+        id: checkAccess
+        uses: actions-cool/check-user-permission@v2
+        with:
+          require: write
+          username: ${{ github.triggering_actor }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Install .NET ${{ matrix.dotnet_version }}
-        # .NET 9 introduced the 'dotnet-sdk-aot' package
-        # .NET 8 introduced the 'dbg' packages
-        # '/etc/os-release' will also match the grep fedora for Fedora derived systems, such as CentOS.
-        timeout-minutes: 10
+      - name: Check User Permission
+        if: steps.checkAccess.outputs.require-result == 'false'
         run: |
-          set -euo pipefail
-          cat /etc/os-release
-          if grep fedora /etc/os-release; then
-            dnf install -y dotnet-sdk-${{ matrix.dotnet_version }}
-            dnf install -y \
-              dotnet-sdk-dbg-${{ matrix.dotnet_version }} \
-              dotnet-runtime-dbg-${{ matrix.dotnet_version }} \
-              aspnetcore-runtime-dbg-${{ matrix.dotnet_version }}
-            if [[ ${{ matrix.dotnet_version }} == 9.* ]]; then
-              dnf install -y dotnet-sdk-aot-${{ matrix.dotnet_version }}
-            fi
-          elif grep alpine /etc/os-release; then
-            if grep edge /etc/os-release; then
-              echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
-            fi
-            apk add dotnet-sdk-${{ matrix.dotnet_version }} dotnet-doc
-            apk add \
-              dotnet-sdk-dbg-${{ matrix.dotnet_version }} \
-              dotnet-runtime-dbg-${{ matrix.dotnet_version }} \
-              aspnetcore-runtime-dbg-${{ matrix.dotnet_version }}
-            if [[ ${{ matrix.dotnet_version }} == 9.* ]]; then
-              apk add dotnet-sdk-aot-${{ matrix.dotnet_version }}
-            fi
-          fi
+          echo "${{ github.triggering_actor }} does not have permissions on this repo."
+          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
+          echo "Job originally triggered by ${{ github.actor }}"
+          exit 1
 
-      - name: Install Test dependencies
-        timeout-minutes: 5
-        run: |
-          if grep fedora /etc/os-release ; then
-            dnf install -y python3 wget $(grep '^Dependencies(dnf): ' README.md | cut -d: -f2-) --skip-broken
-          elif grep alpine /etc/os-release; then
-            apk add python3 wget curl $(grep '^Dependencies(apk): ' README.md | cut -d: -f2-)
-            echo -e '[PostgreSQL]\nDescription=PostgreSQL Unicode\nDriver=/usr/lib/psqlodbcw.so\nUsageCount=1' > /etc/odbcinst.ini
-          fi
+      - name: Check out code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
 
-      - name: Download test runner
-        run: |
-          set -euo pipefail
-          wget --no-verbose https://github.com/redhat-developer/dotnet-bunny/releases/latest/download/turkey.tar.gz
-          tar xf turkey.tar.gz
+      - name: Schedule tests on Testing Farm
+        uses: sclorg/testing-farm-as-github-action@v3.1.2
+        with:
+          api_key: ${{ secrets.TF_API_KEY }}
+          tmt_plan_regex: "ci"
+          compose: ${{ matrix.compose }}
+          variables: ${{ matrix.dotnet_version }}
+    
+  # alpine:
+  #   name: Verify tests pass (alpine)
 
-      - name: Run tests
-        run: |
-          set -euo pipefail
+  #   runs-on: ubuntu-latest
 
-          trait_flags=()
+  #   timeout-minutes: 30
 
-          if [[ ${{ matrix.container_image }} == *ubi8* ]] ; then
-              trait_flags+=( --trait ubi8-repos )
-          fi
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       container_image:
+  #         - docker.io/library/alpine:latest
+  #         - docker.io/library/alpine:edge
+  #       dotnet_version:
+  #         - "8.0"
+  #         - "9.0"
 
-          if [[ ${{ matrix.container_image }} == *ubi9* ]] ; then
-              trait_flags+=( --trait ubi9-repos )
-          fi
+  #   container:
+  #     image: ${{ matrix.container_image }}
+  #     options: --security-opt seccomp=unconfined
 
-          dotnet turkey/Turkey.dll -v --timeout 600 --trait github-ci "${trait_flags[@]}"
-        shell: bash
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Show Logs
-        if: ${{ always() }}
-        run: |
-          set -euo pipefail
-          find -iname '*.log' -exec echo {} \; -exec cat {} \;
+  #     - name: Install .NET ${{ matrix.dotnet_version }}
+  #       timeout-minutes: 10
+
+  #       run: |
+  #         set -euo pipefail
+  #         cat /etc/os-release
+
+  #         if grep edge /etc/os-release; then
+  #           echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
+  #         fi
+  #         apk add dotnet-sdk-${{ matrix.dotnet_version }} dotnet-doc
+  #         apk add \
+  #           dotnet-sdk-dbg-${{ matrix.dotnet_version }} \
+  #           dotnet-runtime-dbg-${{ matrix.dotnet_version }} \
+  #           aspnetcore-runtime-dbg-${{ matrix.dotnet_version }}
+  #         if [[ ${{ matrix.dotnet_version }} == 9.* ]]; then
+  #           apk add dotnet-sdk-aot-${{ matrix.dotnet_version }}
+  #         fi
+      
+  #     - name: Install Test dependencies
+  #       timeout-minutes: 5
+  #       run: |
+  #         apk add python3 wget curl $(grep '^Dependencies(apk): ' README.md | cut -d: -f2-)
+  #         echo -e '[PostgreSQL]\nDescription=PostgreSQL Unicode\nDriver=/usr/lib/psqlodbcw.so\nUsageCount=1' > /etc/odbcinst.ini
+
+  #     - name: Download test runner
+  #       run: |
+  #         set -euo pipefail
+  #         wget --no-verbose https://github.com/redhat-developer/dotnet-bunny/releases/latest/download/turkey.tar.gz
+  #         tar xf turkey.tar.gz    
+
+  #     - name: Run tests
+  #       run: |
+  #         set -euo pipefail
+
+  #         trait_flags=()
+
+  #         if [[ ${{ matrix.container_image }} == *ubi8* ]] ; then
+  #             trait_flags+=( --trait ubi8-repos )
+  #         fi
+
+  #         if [[ ${{ matrix.container_image }} == *ubi9* ]] ; then
+  #             trait_flags+=( --trait ubi9-repos )
+  #         fi
+
+  #         dotnet turkey/Turkey.dll -v --timeout 600 --trait github-ci "${trait_flags[@]}"
+  #       shell: bash
+
+  #     - name: Show Logs
+  #       if: ${{ always() }}
+  #       run: |
+  #         set -euo pipefail
+  #         find -iname '*.log' -exec echo {} \; -exec cat {} \;
